- include/chaiscript/dispatchkit/boxed_number.hpp
defining the preprocessor CHAISCRIPT_PROTECT_DIVIDEBYZERO adds checking of right side values before division arithmetic, allowing the user to safely catch a divide by zero error, rather than dealing with a SIGFPE and having the entire program exit without a choice
> Added (optional) protection against divide by zero exceptions

- include/chaiscript/dispatchkit/bootstrap.hpp
- include/chaiscript/dispatchkit/boxed_number.hpp
- include/chaiscript/language/chaiscript_eval.hpp
- unittests/divide_by_zero_protection.chai
- unittests/future.chai
@lufinkey I've taken your divide by zero protection patches and gotten them ready for merging into ChaiScript.
I made the following changes:
1. Remove macros in favor of function template
2. Make divide by zero protection the default behavior
3. Limit protection to only integer types, floating point returns "Infinity"
4. Make sure the divide by zero is catchable inside the ChaiScript itself
5. Add some unit tests
I'll merge it shortly but thought you might want to see the changes.
> Divide by zero protection

- .decent_ci-Linux.yaml
- include/chaiscript/chaiscript_defines.hpp
- include/chaiscript/dispatchkit/bind_first.hpp
- include/chaiscript/dispatchkit/bootstrap.hpp
- include/chaiscript/dispatchkit/bootstrap_stl.hpp
- include/chaiscript/dispatchkit/register_function.hpp
- include/chaiscript/language/chaiscript_engine.hpp
- include/chaiscript/language/chaiscript_eval.hpp
- include/chaiscript/language/chaiscript_parser.hpp
- samples/example.cpp
- unittests/multithreaded_test.cpp
Fixes all known issues with building / running on ubuntu 14.04 with clang 3.5 and libc++1. Had to work around broken type_traits implementations for const member functions in libc++1. Closes #171
> Libcxx ubuntu 14 04

- src/main.cpp
- unittests/performance.chai
Hi there -- just thought I'd throw this your way, in case you want to integrate it...  If not (or if you want me to change the function name), that's fine.
It's handy when doing benchmarking to have some elapsed time functionality built in to the `chai` app.
> Added elapsed time helper to chai executable

- include/chaiscript/language/chaiscript_parser.hpp
- unittests/hex_escapes.chai
- unittests/octal_escapes.chai
During tests I notices that consecutive octal/hex escape sequences in strings lead to parsing errors (due to open octal/hex sequences not being finished whenever a '\' is encountered).
The second commit is a semantic change to limit the length of hex escape sequence to the maximum that makes sense for the char type used. Without this it's a real problem to have arbitrary text following after a hex escape sequence.
> String escape sequence bug fix

- include/chaiscript/utility/json.hpp
Including chaiscript in multiple translation units can cause link errors.
> Fix multiply defined symbols.

- include/chaiscript/chaiscript_stdlib.hpp
- include/chaiscript/dispatchkit/bootstrap.hpp
- include/chaiscript/dispatchkit/bootstrap_stl.hpp
- include/chaiscript/dispatchkit/dispatchkit.hpp
- include/chaiscript/dispatchkit/operators.hpp
- include/chaiscript/utility/json_wrap.hpp
- include/chaiscript/utility/utility.hpp
- src/stl_extra.cpp
- src/test_module.cpp
This is one attempt to tackle build times of ChaiScript, and also the built size of the stdlib.
Passing `Module&` to/from the functions populating ChaiScript instead of `ModulePtr`, does reduce both build times and size of build binaries, although not at all substantially. The Modules are always owned by a `shared_ptr<>` in the context of use, so there is no risk that the reference becomes invalid.
The diff looks large, but it's pretty mechanical application of the same signature change over and over.
> Pass Module by reference instead of shared ptr

- include/chaiscript/dispatchkit/bootstrap_stl.hpp
- unittests/list_resize.chai
- unittests/vector_reserve.chai
- unittests/vector_resize.chai
C++ **STL** containers **vector** and **list** can be resized from ChaiScript script
Additionally vector can reserve from script, can check current capacity
Adds to vector and list
- resize(size_type n, const value_type& val)
- resize(size_type n)
Adds to vector only
- reserve(size_type n)
- size_type capacity() const
> Expose std::vector and std::list resize, reserve and capacity methods

- include/chaiscript/chaiscript_defines.hpp
- include/chaiscript/language/chaiscript_parser.hpp
- unittests/string_unicode_ascii.chai
- unittests/string_unicode_parse.chai
- unittests/string_unicode_unicode.chai
Allow to use \uABCD - like notation inside values.
E.g. \u0020 codes for whitespace. Real life case - browser JSON parser/generator escapes square brackets, so [ and ] become \u005b and \u005d. Before these changes parsing strings from such browser caused exception because of unknown escape sequence, now values are properly translated during parsing.
Code supports MSVC 2013/2015, GCC > 5 and Clang. On other platforms, codecvt is not available, so fallback is used. This affect parser only if other type of string than std::string is used. For std::string, I think all platforms work where ChaiScript compiles.
> Add UTF-8 escape notation to parser

- include/chaiscript/utility/utility.hpp
- The _utility\utility.hpp_ header receives a proper overload of _add_class_ for scoped enums.
> Added add_class overload for scoped enums.

- cheatsheet.md
Issue this pull request references: # no issue, just saw some incorrect documentation
- Fix a one character issue with cheatsheet.md
> nullify_shared_ptr changing == to = in documentation.

- include/chaiscript/utility/json.hpp
- unittests/json_3.chai
- unittests/json_4.chai
- unittests/json_9.chai
- fix issue #334, where negative numbers loaded from JSON were being
parsed as 0.
- add unit tests to cover these cases.
Issue this pull request references: #334
This is my "alternate solution", possibly preferable (?) because it only affects JSON parsing and not the underlying `chaiscript::parse_num()` function.  The existing JSON parsing code assumes chaiscript::parse_num() would handle negative numbers, which it doesn't.  So you need one fix or the other.
All tests pass (including the new JSON ones I added, which previously would have failed).
Please choose this or my other PR (not both). Thanks!
> Handle negative numbers in JSONParse::parse_number

- .travis.yml
- CMakeLists.txt
- include/chaiscript/chaiscript_defines.hpp
- include/chaiscript/language/chaiscript_engine.hpp
- include/chaiscript/language/chaiscript_unknown.hpp
- samples/fun_call_performance.cpp
- src/main.cpp
- unittests/multithreaded_test.cpp
If CHAISCRIPT_NO_DYNLOAD is defined:
- No need to link with -ldl
- Attempting to call load_module will result in exception
- Attempting to instantiate ChaiScript_Basic without stdlib will result in compilation error
- Options::No_Load_Modules by default
> Ability to disable module loading support at compile time

- include/chaiscript/utility/json.hpp
- unittests/json_14.chai
- also add unit tests to cover some broken (now fixed) cases.
Issue this pull request references: #376
> Fix JSON parsing for floats with negative exponents

- include/chaiscript/utility/json.hpp
Linux compilers interpret "long" as 64 bit, Visual Studio on Windows interprets "long" as 32 bit. In order to remove ambiguity, from_json should use int64_t rather than long when parsing integers.
Issue this pull request references: #368
json.hpp: switch from "long" to "int64_t"
> from_json: change long to int64_t to remove OS ambiguity

- include/chaiscript/language/chaiscript_parser.hpp
V728 An excessive check can be simplified. The '||' operator is surrounded by opposite expressions '* m_position != '\''' and '* m_position == '\'''.  chaiscript_parser.hpp
> fixed PVS-Studio warnings V728

- include/chaiscript/utility/json_wrap.hpp
- unittests/json_15.chai
Issue this pull request references: #399
- make to_json() with an empty Map, Vector or Dynamic_Object return a similar/compatible type (JSON object or array), rather than "null".
- include the fix for #381 (to_json() support for null values), so that can also be unit tested.
- add unit test to validate to_json().
> In to_json(), maintain the "type" of empty maps and vectors

- unittests/static_chaiscript.cpp
Appeared when compiling with MULTITHREAD_SUPPORT_ENABLED=FALSE.
> Fix CHAISCRIPT_NO_THREADS macro redefinition warning

- include/chaiscript/dispatchkit/type_info.hpp
Issue this pull request references: #391 (in part)
Comparing pointers was resulting in random differing behavior between compilations. This fix ensures consistent behavior at least on a given compiler (`before` is implementation specific).
> Critical fix of type_info ordering (less than operator)

- include/chaiscript/language/chaiscript_engine.hpp
- include/chaiscript/language/chaiscript_parser.hpp
- unittests/compiled_tests.cpp
- unittests/eval_file_with_bom.chai
- unittests/file_with_bom.inc
Issue this pull request references: #436
- detect BOM in the same way a symbolic link is detected before the parsing begins and skip it
> Handle BOM in the beginning of the script

- cheatsheet.md
Currently, the example where a lambda function was added to chaiscript didn't work for me.
I use g++7, g++8,g++9 both with c++14 and c++17 mode.
It doesn't work either in clang++-7.
If the lambda is wrapped into a std::function<> it will work again!
I have tested it also for Chaiscript 6, 6.1, 6.1.1 and for develop. It didn't work!
> Update cheatsheet.md: Adding Lambda correction.

- cheatsheet.md
Issue this pull request references: (none)
- fixed link to ChaiScript_Extras repository in `cheatsheet.md`
> cheatsheet: fix link to ChaiScript_Extras

- include/chaiscript/language/chaiscript_engine.hpp
Issue this pull request references: #487
- Explicitly capture `this` for the two lambdas within the engine which currently capture `this` implicitly using `=`, which is deprecated in C++20. This remains backwards compatible with C++14, C++17.
> #487: Fix warning for implicit 'this' lambda capture in C++20.

- CMakeLists.txt
In Linux, the library should be installed to /usr/lib64 on 64bit machine
-
-
-
> Use CMAKE_INSTALL_LIBDIR instead of lib

- include/chaiscript/language/chaiscript_engine.hpp
- include/chaiscript/language/chaiscript_eval.hpp
There are two warnings when compiling with GCC 7.4.1 or clang 5.0.1.
1. warning: explicit by-copy capture of ‘this’ redundant with by-copy capture default
2. warning: typedef ... locally defined but not used [-Wunused-local-typedefs]
This change removes [2] and it compacts the lambda capture clause in [1].
-
-
-
> Fix for warnings: by-copy capture of ‘this’ and unused-local-typedefs

- cheatsheet.md
- Fixed a 'ChaiScritp' typo
- Added c++ formatting to as many examples in cheatsheet.md as I could find. Doesn't look like Linguist supports Chaiscript yet https://github.com/github/linguist/blob/16507700cdf46a78368a571c04d1bc601f62947d/lib/linguist/languages.yml#L1
> fix typo in cheatsheet; add cpp highlighting

- cheatsheet.md
- Fix typo mistake in ranged for loop
> Fix typo mistake in ranged for loop

- appveyor.yml
- include/chaiscript/chaiscript_defines.hpp
- include/chaiscript/dispatchkit/boxed_number.hpp
- include/chaiscript/dispatchkit/dispatchkit.hpp
- include/chaiscript/dispatchkit/function_call_detail.hpp
- include/chaiscript/dispatchkit/function_params.hpp
- include/chaiscript/dispatchkit/function_signature.hpp
- include/chaiscript/dispatchkit/proxy_functions.hpp
- include/chaiscript/dispatchkit/proxy_functions_detail.hpp
- include/chaiscript/dispatchkit/register_function.hpp
- include/chaiscript/dispatchkit/type_conversions.hpp
- unittests/compiled_tests.cpp
Issue this pull request references: #536 (replaces it)
- here I've started with @lefticus branch [`VS_2019_fixes`](https://github.com/ChaiScript/ChaiScript/tree/VS_2019_fixes), merged `develop` into it to get up to date with more recent changes, and then added several other required fixes I've discovered are necessary (discussed in my "code review" of #536). Also, the unit test "Object copy counts" now passes again without the special handling for MSVC.
> Fixes for VS2019 and C++17 compilation

- include/chaiscript/dispatchkit/function_call_detail.hpp
When a script function returning a boolean is called from C++ code, ChaiScript tries to initialize a `Boxed_Number` with the returned value. A *bad any cast* exception is then raised.
The proposed modification checks if the return value is a (possibly *cv-ref* qualified) `bool`, before instantiating the `Boxed_Number` (leading to a `boxed_cast` instead).
> Potential fix for issue ChaiScript#481

- include/chaiscript/utility/stack_vector.hpp
Fixes #547, found by @balint-luko.
> Fix stack_vector.pop_back() pre-decrementing

- include/chaiscript/dispatchkit/type_conversions.hpp
The underlying pair that is dereferenced from the iterator has always `const` qualified `first` member (key type). Therefore, an unnecessary temporary was created and bounded to the const ref to the pair. This could be also fixed with `for (const auto &p : from_map)`.
- remove unwanted copies in a loop of the function template `Type_Conversion map_conversion()`
> map_conversion: copy forced for loop var `p` (incompatible ref type)

- include/chaiscript/dispatchkit/function_call_detail.hpp
- unittests/compiled_tests.cpp
Issue this pull request references: #481
Changes proposed in this pull request:
- implemented unit test which is validating whether a lambda from Chaiscript could return a boolean value without throwing any exception,
- the same test case is checking also whether lambda with boolean return value
could be called peacefully from Chaiscript.
After pull request #503 will be resolved, this test will pass; for now it's producing 2 failed checks:
```
/home/draghan/programming/ChaiScript/my/ChaiScript/cmake-build-debug/compiled_tests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compiled_tests is a Catch v2.2.2 host application.
Run with -? for options
-------------------------------------------------------------------------------
Lambdas can return boolean …
```
> Add unit test covering lambdas returning boolean

- include/chaiscript/dispatchkit/type_conversions.hpp
- unittests/compiled_tests.cpp
Issue this pull request references: [Discussion in forum thread](http://discourse.chaiscript.com/t/convert-complex-chaiscript-types-e-g-map-of-map-to-user-defined-types/143/7)
- add a `pair_conversion()` registration helper, analogous to the existing `vector_conversion()` and `map_conversion()` helpers.
- implement a compiled unit test for the new feature.
> Add pair_conversion registration helper with unit test
