- cheatsheet.md
P.S. I love the cheatsheet, it's very helpful!
> Fixing minor typos in cheatsheet

- cheatsheet.md
- Add example how to expose base member from derived type
- Add example how to use STL
> Add two new examples

- .travis.yml
- include/chaiscript/dispatchkit/bootstrap.hpp
- include/chaiscript/dispatchkit/boxed_number.hpp
- include/chaiscript/dispatchkit/type_info.hpp
This provides the internal support for the types. If you want to do anything with them, that's up to you.
> Add support for char16, char32 and wchar

- include/chaiscript/dispatchkit/boxed_cast_helper.hpp
- include/chaiscript/utility/utility.hpp
- unittests/boxed_cast_test.cpp
- unittests/compiled_tests.cpp
I hope you will consider adding this addition to the helper, so people can use them exactly like the user-type / fun combination.
> Added template specialization in chaiscript::utility::add_class<Enum> to register bulk constants.

- cheatsheet.md
Fixed example code as chaiscript::user_type is a function.
> Fix user_type example in cheatsheet.md

- include/chaiscript/language/chaiscript_prelude_docs.hpp
Issue this pull request references: #259
Changed description from copy-paste to basic description
> Fix description of get_guard()

- samples/example.cpp
Issue this pull request references: #269 
-
-
-
Add the system as global.
> Fix for: samples/example.cpp crashes #269

- include/chaiscript/chaiscript.hpp
- include/chaiscript/chaiscript_defines.hpp
This pull request fix some compiler errors.
> Fix some GCC compiler errors.

- cheatsheet.md
Added information about the existence of the break statement to the loop section of the cheatsheet.
> Add break statement to cheatsheet.md

- include/chaiscript/chaiscript.hpp
This is just a minor documentation fix.
> Fixed a bug in the first example in the docs

- include/chaiscript/language/chaiscript_algebraic.hpp
- include/chaiscript/language/chaiscript_parser.hpp
- include/chaiscript/utility/fnv1a.hpp
Hi,
This simple PR speeds up ~13% of parsing time.
Tested using GCC-6.2.0.
> parser optimization step One

- .travis.yml
> Add osx travis

- readme.md
* Changes Example.cpp's directory "src" => "samples" to match repo.
* Change code example from indented quote to highlighted code block.
> Fixes path reference and code formatting in readme.

- readme.md
- Fixes a small formatting issue in the readme.
> Fix link in readme

- include/chaiscript/chaiscript_defines.hpp
Issue this pull request references: #378 
Though this pull request does not fix the slight inaccuracies noted in issue #378 , it does improve parsing speed by about 10%
> Improved parsing speed of parse_num

- include/chaiscript/language/chaiscript_parser.hpp
Issue this pull request references: #387
> Fix for #387

- include/chaiscript/utility/json_wrap.hpp
- unittests/json_3.chai
Issue this pull request references: #413 
- convert integers to long long.
> fix for #413

- include/chaiscript/utility/json.hpp
- unittests/json_15.chai
Issue this pull request references: #409 
- escape object key strings
> Fix for #409

- include/chaiscript/language/chaiscript_engine.hpp
> Fix potential conversion warning on some platforms

- cheatsheet.md
Issue this pull request references: #18
> Add Switch Statement example

- include/chaiscript/language/chaiscript_parser.hpp
- unittests/multiline.chai
Issue this pull request references: #308
> Add support for chained dot calls.

- include/chaiscript/dispatchkit/type_conversions.hpp
- unittests/compiled_tests.cpp
Issue this pull request references: #433 
When adding a conversion, check if it already exists. If it does, throw an exception.
> Error on double conversion

- cheatsheet.md
Fixed a typo (Mame -> Name) i came across.
-
-
-
> Single typo (Mame -> Name)

- .travis.yml
- CMakeLists.txt
- appveyor.yml
- include/chaiscript/utility/json.hpp
Issue this pull request references: #454 
Attempt to update CI configuration for the build to pass with new C++ standard.
> Ci fix after moving to cpp17

- cheatsheet.md
Issue this pull request references: #451 
- Simplified the part about ChaiScript initialization
- Added a link to the ChaiScriptExtras helper library
- Removed the Subsection about built-ins, because they are not longer in the code
> Updated cheatsheet.md

- cheatsheet.md
`.push_back_ref()`.... Saved some performance issues I was having.
> docs: Add push_back_ref() note

- include/chaiscript/language/chaiscript_engine.hpp
> Fix description of ChaiScriptBasic::use

- readme.md
> docs: Fix gendering

- include/chaiscript/dispatchkit/type_conversions.hpp
- unittests/compiled_tests.cpp
Reverts ChaiScript/ChaiScript#482
> Revert "Add pair_conversion registration helper with unit test"
